### PR TITLE
Twigintegration

### PR DESCRIPTION
**Pull request by delatbabel**
I'm not sure if this is going to work yet or not.  I will push it to the end of my own 3.0 branch and see what happens.

This PR merges in functionality from TwigBridge so that twig templates and blade templates can each be run through the StringBladeCompiler.

Take a look and let me know what you think.

### CODE REVIEW

**Comment by delatbabel** [comment]
I have done some basic testing and it appears to work for me.

**Comment by delatbabel** [comment]
On second look it's not actually working, I'm getting a Twig exception thrown. I'll take a closer look tomorrow.

**Comment by delatbabel** [comment]
It's working now to the extent where the twig template gets rendered but the view data is not available to the compiled twig template. I may have to abandon this approach and have a look at doing it differently. It was worth a try, though.

**Comment by TerrePorter** [comment]
I'm not familiar with the twig compiler, not sure what to offer. Anything is worth a try, even when it doesn't work, that it is how innovation happens.

**Comment by delatbabel** [comment]
I've figured out something else to try. I will abandon this attempt for now but like you say, this is how innovation happens.

**Pull request closed without merging**
