### PR TITLE
Laravel 5.4 compatibility

### PR DESCRIPTION
**Pull request by SuperSeb92**
Breaks tests which need updating (many due to using app('translator')->get() rather than the Lang::get() facade), but updates to Laravel's recent changes and brings 5.4 compatibility.

I guess this will need putting in a 3.4 branch?

### CODE REVIEW

**Comment by TerrePorter** [comment]
@SuperSeb92 Thanks for making these updates. I had yet to get to look at 3.4 version of Laravel. I'll try to take a look this weekend at the code and push a release version for people to use. Awesome update, thanks again.

**Comment by pdbreen** [comment]
Hi - Im in the process of updating a site to Laravel 5.4 which led me here as it was using StringBlade v2.*@dev which was able to work through Laravel 5.3 for my use case which only required \StringView::make().  While its great to see work on adding 5.4 compatibility, I'm concerned about the amount of core framework code that is being replicated & replaced to add this functionality (ie, Factory, FileViewFinder, BladeCompiler, ViewServiceProvider).  Unless I'm missing something, any framework patches to the replicated files would require identical patching in this repo.  

While this branch is functioning in my laravel 5.4 testing, is there a way to expose only \StringView::make() without requiring so much core code replacement (ie, without replacing the native ViewServiceProvider)?  

Update:  since I wasn't relying on the caching features of StringBlade, I've ended up switching to a lighter weight compile & render technique described here:  https://laracasts.com/discuss/channels/general-discussion/render-template-from-blade-template-in-database

**Comment by TerrePorter** [comment]
@pdbreen take a look at https://github.com/TerrePorter/StringBladeCompiler/issues/11 @delatbabel modified the 3.0 version to extend the core classes instead, which does use less code. The post also explains why it was done the way it is in the first place. I never made it to update the 3.3 code to use extend, kind of swamped on a project currently, but it is still on the list. Either way, glad you figure out something that works.

**Comment by pdbreen** [comment]
Thanks @TerrePorter - definitely understand time pressures and appreciate you making this available in the first place!  If you do get time, you might want to take a look at how laravel-handlebars added a new compiler using only a service provider.  Not sure if this approach would work for you since you are doing a bit more with the caching and what not, but wanted to pass it on in case its helpful:

https://github.com/ProAI/laravel-handlebars/blob/master/src/HandlebarsServiceProvider.php

Thanks again!

**Pull request merged**
