### PR TITLE
Laravel 5.6

### PR DESCRIPTION
**Pull request by avengerweb**

### CODE REVIEW

**Comment by avengerweb** [comment]
issue #32

**Comment by vokomarov** [comment]
@TerrePorter Why this PR still opened? Could you check and merge this please?

**Comment by TerrePorter** [comment]
@VovikeMS Please accept my apology. Life has been a bit crazy here. I've created a new branch 3.6 for this update. I've also published a copy so that it should work with composer.

**Comment by vokomarov** [comment]
@TerrePorter Thanks a lot for a quick action, no need to apology 😄

**Pull request merged**
