### PR TITLE
Slim down StringBladeCompiler code

### PR DESCRIPTION
**Pull request by delatbabel**
Slim down StringBladeCompiler code by stripping out code that just copied the upstream (Laravel) code.

Significant changes:
- class Factory now extends Illuminate\View\Factory and calls parent::make if the input is not an array.
- class FileViewFinder removed.
- interface ViewFinderInterface removed.
- fix unit tests.
- PSR-2 compliance.
- test runner added.

### CODE REVIEW

**Comment by delatbabel** [comment]
Resolves #11

**Comment by delatbabel** [comment]
Tests are passing but I guess it's worth doing some more extensive testing before tagging this because there's still a lot of coverage missing from the unit tests.  I can't see why this wouldn't work, though.

**Comment by TerrePorter** [comment]
Very nice! I like it. 

I've took a brief look and your code does a great job at reducing the project and making it more extendable. I would agree with wanting more of the test coverage.

Beyond that it looks very promising.

**Comment by delatbabel** [comment]
Hrm, now I want to start on twig integration with these changes already incorporated. I'll put that onto a new branch while you're absorbing this change.

**Comment by TerrePorter** [comment]
I've had a family emergency Monday night that has put me behind for everything. So I've not gotten much further on looking at this in depth. If I can get caught up today I might be able to take a good look tomorrow or perhaps later tonight.

**Comment by TerrePorter** [comment]
I finally got a little time to take a good look. I have it working in both Laravel 5.1 and 5.2, without any errors - so far. A few more things to test but looks good. I'll work in some more time over the next few days.

**Comment by TerrePorter** [comment]
@delatbabel Ok, I could find nothing that didn't work as expected. So I've merged the pull in to the project. Awesome job on the modifications.

**Pull request merged**
