### PR TITLE
Add Laravel 5.7 Support

### PR DESCRIPTION
**Pull request by mikerogne**

### CODE REVIEW

**Comment by mikerogne** [comment]
I should also note that this is only for Laravel 5.7 actually... because of this (merged) PR: https://github.com/laravel/framework/pull/23532/files

**Comment by TaProhm** [comment]
Thx for this compiler. Laravel 5.7 support would be great.

**Comment by vokomarov** [comment]
@TerrePorter Hi, thanks for your job. Is there any problems with this PR? Because since 1 month this PR still opened and no comments. Is project are alive?
Thanks.

**Comment by mikerogne** [comment]
I've been using this in production since I submitted the PR.

In my composer.json I have:

```
"require": {
  "wpb/string-blade-compiler": "dev-laravel-5.7"
},
"repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/mikerogne/StringBladeCompiler"
  }
]
```

That'll use my patched version of this library. Obviously you can see the updated source code yourself. This composer.json info is documented here: https://getcomposer.org/doc/05-repositories.md#vcs

**Comment by vokomarov** [comment]
Thanks @mikerogne , already used your patch 😄 
Waiting for @TerrePorter  will back.

**Comment by TerrePorter** [comment]
Sorry didnt get notice about the patch request and have been busy.

**Pull request merged**
